site_name: learningOrchestra Docs
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Guide: 
    - Microservices REST APIs: 
      - Database API: database-api.md
      - Projection API: projection-api.md
      - Data Type API: datatype-api.md
      - Histogram API: histogram-api.md
      - t-SNE API: t-sne-api.md
      - PCA API: pca-api.md
      - Model builder API: modelbuilder-api.md
    - python-client APIs: python-apis.md
theme:
  name: readthedocs
  features:
    - instant
    - search.highlight
  plugins:
    - search
